language: ruby
rvm:
  - 2.6.3
before_install:
  - gem install bundler
before_script:
  - psql -c 'create database "amazon-asin_test";' -U postgres
script:
  - mkdir -p spec && bundle exec rspec spec
services:
  - postgresql
