language: ruby
rvm:
  - 2.6.3
before_install:
  - gem install bundler
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  - export CHROME_BIN=chromium-browser
  - psql -c 'create database "amazon-asin_test";' -U postgres
script:
  - mkdir -p spec && bundle exec rspec spec
services:
  - postgresql
